//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public string Reason { get; set; }
        public string ReasonType { get; set; }
        public bool IsConfirm { get; set; }
    
        public virtual User User { get; set; }
    }
}
